spring:
  application:
    name: medtrack
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:medtrack}
    username: ${DB_USER:medtrack}
    password: ${DB_PASSWORD:medtrack}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

server:
  port: ${SERVER_PORT:8080}
